name: lexie
description: An asychronous lexing framework for Dart.
version: 0.0.1
author: R.S. Schermer <roland0507@gmail.com>
homepage: https://github.com/RSSchermer/lexie.dart
documentation:
environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  resource: '>=2.0.2 <2.1.0'

dev_dependencies:
  test: '^0.12.17'
